### ISSUE TITLE
Does not redirect

### ISSUE THREAD

**Issue by ahmed374b** [PayGate/PayWeb_Gravity_Forms#10]
Hi 
I have been getting the error below

(index):543 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at HTMLIFrameElement.<anonymous> ((index):543)
    at HTMLIFrameElement.dispatch (fc0c975cfeda2be36628c923ee7f11c1.js:3)
    at HTMLIFrameElement.v.handle (fc0c975cfeda2be36628c923ee7f11c1.js:3)
(anonymous) @ (index):543
dispatch @ fc0c975cfeda2be36628c923ee7f11c1.js:3
v.handle @ fc0c975cfeda2be36628c923ee7f11c1.js:3

**Comment by bruce-atkinson** [comment]
Hi @ahmed374b, we are unable to duplicate this issue our side.

Please kindly send through details to our support team at support@paygate.co.za with additional details to replicate the issue.
