### ISSUE TITLE
GravityForms export is missing "Approved" & "Declined" status

### ISSUE THREAD

**Issue by kennonb** [PayGate/PayWeb_Gravity_Forms#13]
Thanks for this plugin. It's working great! There's one thing I've run into that I'm not quite sure how to handle, so I figured I'd ask first to see if there's something I'm missing.

When exporting entries, and using a conditional, "Payment Status" is missing both the "Approved" and "Declined" options.

Example: 
<img width="737" alt="CleanShot 2022-10-25 at 22 22 14@2x" src="https://user-images.githubusercontent.com/76159/197919624-b2611c63-8350-41f3-8e08-082dc26b7948.png">

Is there anyway to get those options in the export select field, or do I have something mis-configured? 

Thanks!

**Comment by bruce-atkinson** [comment]
Hi @kennonb 

Sadly, there are limitations on the export of entries for payment forms. 

Please try out the ‘Paid’ and ‘Failed’ conditions and let us know if this achieves what you want to achieve.

**Comment by kennonb** [comment]
Thanks @appinlet. Unfortunately I've tried that and it doesn't appear to include any data when selected. The transactions are only showing as "Approved" or "Declined" in the entries table. I appreciate your help. 😊
