### ISSUE TITLE
Post Payment Actions (Gravity Forms “delayed payment” system)

### ISSUE THREAD

**Issue by waddalouw** [PayGate/PayWeb_Gravity_Forms#16]
Include option to process actions after payment, like writing an entry to a Google Sheet.

Example implementation:

- [Gravity Forms Google Sheets](https://gravitywiz.com/documentation/gravity-forms-google-sheets/#feed-settings:~:text=GP%20Google%20Sheets%20integrates%20with%20Gravity%20Forms%20%E2%80%9Cdelayed%20payment%E2%80%9D%20system%2C%20allowing%20feeds%20to%20only%20be%20processed%20after%20a%20payment%20has%20been%20received.%20This%20means%20you%20can%20wait%20to%20insert%20the%20entry%20row%20into%20a%20Google%20Sheet%20until%20after%20the%20user%20has%20completed%20their%20payment.)

Documentation:

- [How to Add Delayed Payment Support to a Feed Add-On](https://docs.gravityforms.com/add-delayed-payment-support-feed-add/)

**Comment by bruce-atkinson** [comment]
Hi @waddalouw,

Please kindly submit this change request to [support@payfast.help](mailto:support@payfast.help).
