### ISSUE TITLE
Add User-Customizable Payment References to Plugin

### ISSUE THREAD

**Issue by waddalouw** [PayGate/PayWeb_Gravity_Forms#17]
**Current Behaviour:**

Currently, the plugin defaults to using the form entry ID as the payment reference.

**Proposed Feature:**

Introducing a "Reference" section in the plugin settings would provide valuable customization options:

1. Use default reference (entry ID): Maintain the existing behaviour for streamlined use.
2. Select a field to use as reference: Allow users to pick a relevant existing field (e.g., invoice number, customer ID) to align with their payment reconciliation processes.
3. Hash the entry ID and use that as a payment reference: Offer a more secure approach by applying a hashing function (e.g., MD5, SHA-1) to the entry ID, creating an obfuscated reference.

**Benefits:**

- Adaptability: Accommodates varying payment processor requirements and diverse user workflows.
- Improved Reconciliation: Enables users to leverage more meaningful references for easier reconciliation on their payment processor's end.
- Potential Security Enhancement: The hashing option could provide an added layer of security if desired.

**Comment by bruce-atkinson** [comment]
Hi @waddalouw,

Please kindly submit this change request to [support@payfast.help](mailto:support@payfast.help).
