### ISSUE TITLE
Form not continuing to PayGate for payment with CORS issue

### ISSUE THREAD

**Issue by fbrill** [PayGate/PayWeb_Gravity_Forms#7]
When the form is embedded without AJAX, it just continues to the thank you page, and when AJAX is on, I get this CORS error:

You can see the form at: https://theboxfashion.co.za/join/checkout-option-01/?flow=1

<img width="560" alt="Screenshot 2020-10-19 at 14 46 04" src="https://user-images.githubusercontent.com/5826359/96452971-1ecaf800-121a-11eb-90c7-9535551dda5d.png">

**Comment by bruce-atkinson** [comment]
Unfortunately, @fbrill, AJAX isn't supported in some theme and for contexts due to the nature of how the transaction process is handled in PayWeb.

**Comment by fbrill** [comment]
Thank you for the feedback @appinlet - good to know AJAX is not supported. As mentioned the behaviour was still to skip the entire PayGate process and go straight to the thank you page. It turns out that if you embed the form through php (directly into a template file) - you need to [embed/enqueue](https://docs.gravityforms.com/gravity_form_enqueue_scripts/) the gform scripts and styles manually for that form.
