### ISSUE TITLE
Site Health Rest API Error

### ISSUE THREAD

**Issue by Mikewdp** [PayGate/PayWeb_Gravity_Forms#8]
Hi there

The PayGate Gravity Forms plugin v2.2.11 for Gravity Forms v2.4.18 seems to create an error on WordPress version 5.7.2, any ideas on how to fix this? I updated my gravity form to the latest version Version 2.5.0.2  but this didn't solve the problem. Kindly advise on the solution.
Please see attached, the error only shows up when The PayGate Gravity Forms plugin v2.2.11 for Gravity Forms v2.4.18 is activated.

![1c](https://user-images.githubusercontent.com/84253511/118382016-ff018400-b5f0-11eb-9ee1-5a424c2810ff.png)
the error details caused by the PayGate Gravity Forms plugin v2.2.11  on WordPress site health.

**Comment by bruce-atkinson** [comment]
Hi @Mikewdp,

Please kindly send through details to replicate to the support team at support@paygate.co.za.
