### ISSUE TITLE
Plugin breaks output buffering

### ISSUE THREAD

**Issue by markparnell** [PayGate/PayWeb_Gravity_Forms#9]
We use output buffering extensively in our theme and after implementing PayGate on a client site found that this was no longer working as it should. Eventually we identified that the problem is two calls to `ob_start()` in the plugin without corresponding calls to close the buffer (e.g. `ob_end_clean()`.

The offending calls are on lines 62 and 103 of `paygate.php` - removing them both along with the unnecessary call to `ob_clean()` on line 104 resolves the issue.

We've made this change locally, but would appreciate it being included in the next update so we don't have to keep manually applying the fix.

**Comment by bruce-atkinson** [comment]
Mank thanks. @markparnell please note these changes are present in the current release.
